### ISSUE TITLE
Bulk call on getEmployeeUD, similar to getStudentUD

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/employee-hr#19]
Would it be possible to be able to return all employee UD fields so that a school is not getting hundreds of API requests to sync this?

This would be similar in implementation to the getStudentUD:

Add a new conditional field currentstatus, change the required field code to a conditional field. Add new validations for code and currentstatus.

**Comment by scottetass** [comment]
Hi cwool,

Whilst this is a great suggestion, returning an array of employees instead of returning a single employee, as the endpoint does now, would be a breaking change for all consumers of this particular endpoint.

As our new API offering will be released later in the year, we are going to defer any breaking changes in old APIs, unless critical.

I've noted down the requirement and it will be something that we can certainly look at when moving this across to the new API.

Regards, Scott
